#Spring DB Setting
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.username=sa
spring.datasource.password=

#H2 Setting
    h2:
        console:
            enabled: true  # H2 Console? Using Y/N
            path: /h2-console  # H2 Console Server Path
# Database Setting Info (Database? H2? ???? ?? H2?? ?? ??)

#jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#        ddl-auto: create        # DB ??? ?? (none, create, create-drop, update, validate)
#    properties:
#        hibernate:
#            dialectz: org.hibernate.dialect.H2Dialect
#            format_sql: true      # ?? ?? ?? (??)
#            show_sql: true        # ?? ?? ??

#thymeleaf ??
spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
